name: dart_lz4
version: 0.0.1
author: Achilleas Anagnostopoulos
description: Dart native lz4 extension
homepage: https://github.com/achilleasa/dart_lz4
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
